

Citizen.CreateThread(function()

while true do
    Citizen.Wait(0)
    SetRelationshipBetweenGroups(1, GetHashKey("AMBIENT_GANG_HILLBILLY"), GetHashKey('PLAYER'))
    SetRelationshipBetweenGroups(1, GetHashKey("AMBIENT_GANG_BALLAS"), GetHashKey('PLAYER'))
    SetRelationshipBetweenGroups(1, GetHashKey("AMBIENT_GANG_MEXICAN"), GetHashKey('PLAYER'))
    SetRelationshipBetweenGroups(1, GetHashKey("AMBIENT_GANG_FAMILY"), GetHashKey('PLAYER'))
    SetRelationshipBetweenGroups(1, GetHashKey("AMBIENT_GANG_MARABUNTE"), GetHashKey('PLAYER'))
    SetRelationshipBetweenGroups(1, GetHashKey("AMBIENT_GANG_SALVA"), GetHashKey('PLAYER'))
    SetRelationshipBetweenGroups(1, GetHashKey("AMBIENT_GANG_LOST"), GetHashKey('PLAYER'))
    SetRelationshipBetweenGroups(1, GetHashKey("AMBIENT_GANG_CULT"), GetHashKey('PLAYER'))
    SetRelationshipBetweenGroups(1, GetHashKey("AMBIENT_GANG_WEICHENG"), GetHashKey('PLAYER'))
    SetRelationshipBetweenGroups(1, GetHashKey("DEALER"), GetHashKey('PLAYER'))
    SetRelationshipBetweenGroups(1, GetHashKey("GANG_1"), GetHashKey('PLAYER'))
    SetRelationshipBetweenGroups(1, GetHashKey("GANG_2"), GetHashKey('PLAYER'))
    SetRelationshipBetweenGroups(1, GetHashKey("GANG_9"), GetHashKey('PLAYER'))
    SetRelationshipBetweenGroups(1, GetHashKey("GANG_10"), GetHashKey('PLAYER'))
    SetRelationshipBetweenGroups(1, GetHashKey("FIREMAN"), GetHashKey('PLAYER'))
    SetRelationshipBetweenGroups(1, GetHashKey("MEDIC"), GetHashKey('PLAYER'))
    SetRelationshipBetweenGroups(1, GetHashKey("COP"), GetHashKey('PLAYER'))
    SetRelationshipBetweenGroups(1, GetHashKey("SPECIAL"), GetHashKey('PLAYER'))
    SetRelationshipBetweenGroups(1, GetHashKey("MISSION2"), GetHashKey('PLAYER'))
    SetRelationshipBetweenGroups(1, GetHashKey("MISSION3"), GetHashKey('PLAYER'))
    SetRelationshipBetweenGroups(1, GetHashKey("MISSION4"), GetHashKey('PLAYER'))
    SetRelationshipBetweenGroups(1, GetHashKey("MISSION5"), GetHashKey('PLAYER'))
    SetRelationshipBetweenGroups(1, GetHashKey("MISSION6"), GetHashKey('PLAYER'))
    SetRelationshipBetweenGroups(1, GetHashKey("MISSION7"), GetHashKey('PLAYER'))
    SetRelationshipBetweenGroups(1, GetHashKey("MISSION8"), GetHashKey('PLAYER'))
end
end)
